### PR TITLE
2020.2 support v2

### PR DESCRIPTION
**Pull request by mskonovalov**
the change cae0139ad663476b0baabebfe522d73cd8a79aa6

### CODE REVIEW

**Review by uri-canva — CHANGES_REQUESTED** [review]
What's the relationship between this and https://github.com/Canva/bazelbuild-intellij/pull/6? Do I need to review both?

**Comment by mskonovalov** [comment]
it is a bit different approach see this comment https://github.com/Canva/bazelbuild-intellij/pull/6#commitcomment-41162209

it is pretty similar except changes in `plugin.xml`

**Comment by mskonovalov** [comment]
this one doesn't seem to work :(

**Comment by mskonovalov** [comment]
ok, I don't understand why but this one shows error "ClassNotFound MacroLineMarkerProvider.java"
so I'm closing this and going forward with the first one

**Pull request closed without merging**
